include:
  - "**/*.rb"
exclude:
  - "test/**/*"
  - "spec/**/*"
  - "vendor/**/*"
  - "tmp/**/*"
require:
  - solargraph-rails
plugins:
  - solargraph-rails
reporters:
  - rubocop
  - require_not_found
max_files: 5000
