version: '2.1'
services:
  db:
    image: "postgres:11"
    ports:
      - "5432"
    environment:
      - "POSTGRES_USER=journal_administration"
      - "POSTGRES_PASSWORD=journal_administration"
      - "PGDATA=${PGDATA:-/var/lib/postgresql/data}"
